### ISSUE TITLE
ERROR! Unexpected Exception, this is probably a bug: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by hille721** [hille721/ansible-variables#12]
Running `ansible-variables -v` or  `ansible-variables -vvv` will lead to following error if there is an empty file present in the inventory host_vars or group_vars: 

```
ERROR! Unexpected Exception, this is probably a bug: argument of type 'NoneType' is not iterable
the full traceback was:

Traceback (most recent call last):
  File "/home/hille/gitrepos/plminfra_ansible/.venv/lib/python3.9/site-packages/ansible/cli/__init__.py", line 647, in cli_executor
    exit_code = cli.run()
  File "/home/hille/gitrepos/plminfra_ansible/.venv/lib/python3.9/site-packages/ansible_variables/cli/variables.py", line 116, in run
    files = variable.file_occurrences(loader=self.loader)
  File "/home/hille/gitrepos/plminfra_ansible/.venv/lib/python3.9/site-packages/ansible_variables/utils/vars.py", line 85, in file_occurrences
    if self.name in loader.load_from_file(ffile):
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by hille721** [comment]
tests now also reproducing the issue, see: https://github.com/hille721/ansible-variables/actions/runs/4778881472/jobs/8495588545#step:5:235
